version: "3"

tasks:
  start:
    cmds:
      - python3 manage.py runserver
    silent: false
  bd:
    deps: [format]
    cmds:
      #      - npx webpack build --mode=production
      - npx webpack build --mode=development
    silent: false
  format:
    cmds:
      - npx prettier --write .
    silent: false
